INSERT INTO category_product (name) VALUES("Elektronik");
INSERT INTO category_product (name) VALUES("Kebutuhan sekolah");
INSERT INTO category_product (name) VALUES("Pakaian pria");
INSERT INTO category_product (name) VALUES("Pakaian wanita");
INSERT INTO category_product (name) VALUES("Makanan");
INSERT INTO category_product (name) VALUES("Sport");
INSERT INTO category_product (name) VALUES("Gadget dan Handphone");
INSERT INTO category_product (name) VALUES("otomotif");
INSERT INTO category_product (name) VALUES("Alat rumah tangga");
INSERT INTO category_product (name) VALUES("Musik");